USE EmpresaPedidos;

-- UPDATE COM SUBSELECT
UPDATE CONTATO
SET OBSERVACAO = 'ELEITO 1° TURNO'
WHERE FKTIPOCONTATO IN(
	SELECT IDTIPOCONTATO FROM TIPOCONTATO
    WHERE NOMETIPOCONTATO = 'PREFEITO'
);

-- UPDATE COM JOIN
UPDATE CONTATO AS C
INNER JOIN TIPOCONTATO AS TC ON TC.IDTIPOCONTATO = C.FKTIPOCONTATO
SET OBSERVACAO = 'ELEITO 1° TURNO'
WHERE TC.NOMETIPOCONTATO = 'PREFEITO';

-- EXERCICIO: ELABORE UMA INSTRUÇÃO SQL PARA ATUALIZAR O VALOR TOTAL DO PEDIDO (PEDIDO.VALORTOTAL) POR MEIO DE UM SELECT
-- COM FUNÇÃO DE AGREGAÇÃO E JUNÇÃO NAS TABELAS PEDIDOITENS E PRODUTO
SELECT SUM(PR.VALORUNITARIO * PI.QUANTIDADE) AS VALOR_TOTAL
FROM PEDIDOITENS PI
INNER JOIN PRODUTO PR ON PI.FKPRODUTO = PR.IDPRODUTO
WHERE PI.FKPEDIDO = 1;

-- CRIAR VARIÁVEL: SET @codPedido := 1;

UPDATE PEDIDO
SET VALORTOTAL = (
	SELECT SUM(PR.VALORUNITARIO * PI.QUANTIDADE) AS VALOR_TOTAL
	FROM PEDIDOITENS PI
	INNER JOIN PRODUTO PR ON PI.FKPRODUTO = PR.IDPRODUTO
    WHERE PI.FKPEDIDO = 1
)
WHERE IDPEDIDO = 1;

-- 3) Liste o valor total de pedidos, por cliente, mês a mês no ano de 2021, no formato a seguir. 
-- Utilize o UNION para juntar os valores de cada mês em um único SELECT.

-- USA UMA VIEW (COMO SE FOSSE UMA TABELA TEMPORÁRIA), DÁ PARA DAR SELECT NELA
-- CREATE VIEW SOMATOTAL AS

