CREATE SCHEMA INSERT_EXCEL_2;
USE INSERT_EXCEL_2;

SELECT * FROM MUNICIPIOS_AREA;
SELECT * FROM MUNICIPIOS_REGIOES;
SELECT * FROM CIDADES;

/*
-- NÃO TRAZ NADA, PQ OS TIPOS DA FK E PK SÃO != E OS CÓDIGOS DA CIDADE TBM

SELECT CIDADES.*, MUNICIPIOS_REGIOES.*, MUNICIPIOS_AREA.*
FROM CIDADES
INNER JOIN MUNICIPIOS_REGIOES ON CIDADES.CODIGO_CIDADE = MUNICIPIOS_REGIOES.IDMUNICIPIO
INNER JOIN MUNICIPIOS_AREA ON MUNICIPIOS_AREA.CD_MUN = MUNICIPIOS_REGIOES.IDMUNICIPIO;
*/

-- ATIVIDADE

-- 1
SELECT NOME_CIDADE, CODIGO_CIDADE FROM CIDADES
WHERE NOME_CIDADE LIKE '%vista%'
ORDER BY NOME_CIDADE;

-- 2
SELECT NOME_CIDADE, CODIGO_CIDADE, ESTADO FROM CIDADES
WHERE ESTADO IN('SP', 'RJ', 'MG', 'ES')
ORDER BY ESTADO, NOME_CIDADE;

-- 3
SELECT NOME_CIDADE, CODIGO_CIDADE, ESTADO, POPULACAO_TOTAL FROM CIDADES
WHERE POPULACAO_TOTAL > 1000000
ORDER BY POPULACAO_TOTAL DESC;

-- 4
SELECT NOME_CIDADE, CODIGO_CIDADE, ESTADO, POPULACAO_TOTAL FROM CIDADES
WHERE POPULACAO_TOTAL >= 10000 AND POPULACAO_TOTAL <= 13000;

-- 5
SELECT NOME_CIDADE, CODIGO_CIDADE, ESTADO, POPULACAO_TOTAL FROM CIDADES
ORDER BY POPULACAO_TOTAL DESC, ESTADO, NOME_CIDADE
LIMIT 10;