-- STORED PROCEDURES
USE EmpresaPedidos;

-- TROCA O ELEMENTO DE FIM DE BLOCO DE ';' POR '//'
-- INTO: ENFIA O RESULTADO NA SAÍDA
DELIMITER // 

CREATE PROCEDURE sp_valorpedido(IN codPedido INT, OUT valorTotalPedido DECIMAL(10,2))
BEGIN
	SELECT SUM(PR.VALORUNITARIO * PI.QUANTIDADE) INTO valorTotalPedido
	FROM PEDIDOITENS PI
	INNER JOIN PRODUTO PR ON PI.FKPRODUTO = PR.IDPRODUTO
	WHERE PI.FKPEDIDO = codPedido;
END;

//

DELIMITER ;

-- NÃO PRECISA DECLARAR A VARIÁVEL @RESULTADO ANTES
-- SÓ INFORMA SE DEU CERTO OU ERRADO
CALL sp_valorpedido(2, @resultado);

SELECT @resultado;