USE EmpresaPedidos;

-- UPDATE COM SUBSELECT
UPDATE CONTATO
SET OBSERVACAO = 'ELEITO 1° TURNO'
WHERE FKTIPOCONTATO IN(
	SELECT IDTIPOCONTATO FROM TIPOCONTATO
    WHERE NOMETIPOCONTATO = 'PREFEITO'
);

-- UPDATE COM JOIN
UPDATE CONTATO AS C
INNER JOIN TIPOCONTATO AS TC ON TC.IDTIPOCONTATO = C.FKTIPOCONTATO
SET OBSERVACAO = 'ELEITO 1° TURNO'
WHERE TC.NOMETIPOCONTATO = 'PREFEITO';

-- EXERCICIO: ELABORE UMA INSTRUÇÃO SQL PARA ATUALIZAR O VALOR TOTAL DO PEDIDO (PEDIDO.VALORTOTAL) POR MEIO DE UM SELECT
-- COM FUNÇÃO DE AGREGAÇÃO E JUNÇÃO NAS TABELAS PEDIDOITENS E PRODUTO
SELECT SUM(PR.VALORUNITARIO * PI.QUANTIDADE) AS VALOR_TOTAL
FROM PEDIDOITENS PI
INNER JOIN PRODUTO PR ON PI.FKPRODUTO = PR.IDPRODUTO
WHERE PI.FKPEDIDO = 1;

-- CRIAR VARIÁVEL: SET @codPedido := 1;

UPDATE PEDIDO
SET VALORTOTAL = (
	SELECT SUM(PR.VALORUNITARIO * PI.QUANTIDADE) AS VALOR_TOTAL
	FROM PEDIDOITENS PI
	INNER JOIN PRODUTO PR ON PI.FKPRODUTO = PR.IDPRODUTO
    WHERE PI.FKPEDIDO = 1
)
WHERE IDPEDIDO = 1;

-- 3) Liste o valor total de pedidos, por cliente, mês a mês no ano de 2021, no formato a seguir. 
-- Utilize o UNION para juntar os valores de cada mês em um único SELECT.

-- USA UMA VIEW (COMO SE FOSSE UMA TABELA TEMPORÁRIA), DÁ PARA DAR SELECT NELA
-- CREATE VIEW SOMATOTAL AS
ALTER VIEW SOMATOTAL AS
SELECT NOME, YEAR(DATAPEDIDO) AS AN0, SUM(VALORTOTAL) AS JAN, 0 AS FEV, 0 AS MAR, 0 AS ABR, 0 AS MAI, 0 AS JUN, 
0 AS JUL, 0 AS AGO, 0 AS 'SET', 0 AS 'OUT', 0 AS NOV, 0 AS DEZ, SUM(VALORTOTAL) AS TOTAL
FROM PEDIDO
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = PEDIDO.FKCLIENTE
WHERE MONTH(DATAPEDIDO) = 1
GROUP BY NOME, YEAR(DATAPEDIDO)
UNION
SELECT NOME, YEAR(DATAPEDIDO) AS AN0, 0 AS JAN, SUM(VALORTOTAL) AS FEV, 0 AS MAR, 0 AS ABR, 0 AS MAI, 0 AS JUN, 
0 AS JUL, 0 AS AGO, 0 AS 'SET', 0 AS 'OUT', 0 AS NOV, 0 AS DEZ, SUM(VALORTOTAL) AS TOTAL
FROM PEDIDO
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = PEDIDO.FKCLIENTE
WHERE MONTH(DATAPEDIDO) = 2
GROUP BY NOME, YEAR(DATAPEDIDO)
UNION
SELECT NOME, YEAR(DATAPEDIDO) AS AN0, 0 AS JAN, 0 AS FEV, SUM(VALORTOTAL) AS MAR, 0 AS ABR, 0 AS MAI, 0 AS JUN, 
0 AS JUL, 0 AS AGO, 0 AS 'SET', 0 AS 'OUT', 0 AS NOV, 0 AS DEZ, SUM(VALORTOTAL) AS TOTAL
FROM PEDIDO
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = PEDIDO.FKCLIENTE
WHERE MONTH(DATAPEDIDO) = 3
GROUP BY NOME, YEAR(DATAPEDIDO)
UNION
SELECT NOME, YEAR(DATAPEDIDO) AS AN0, 0 AS JAN, 0 AS FEV, 0 AS MAR, SUM(VALORTOTAL) AS ABR, 0 AS MAI, 0 AS JUN, 
0 AS JUL, 0 AS AGO, 0 AS 'SET', 0 AS 'OUT', 0 AS NOV, 0 AS DEZ, SUM(VALORTOTAL) AS TOTAL
FROM PEDIDO
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = PEDIDO.FKCLIENTE
WHERE MONTH(DATAPEDIDO) = 4
GROUP BY NOME, YEAR(DATAPEDIDO)
UNION
SELECT NOME, YEAR(DATAPEDIDO) AS AN0, 0 AS JAN, 0 AS FEV, 0 AS MAR, 0 AS ABR, SUM(VALORTOTAL) AS MAI, 0 AS JUN, 
0 AS JUL, 0 AS AGO, 0 AS 'SET', 0 AS 'OUT', 0 AS NOV, 0 AS DEZ, SUM(VALORTOTAL) AS TOTAL
FROM PEDIDO
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = PEDIDO.FKCLIENTE
WHERE MONTH(DATAPEDIDO) = 5
GROUP BY NOME, YEAR(DATAPEDIDO)
UNION
SELECT NOME, YEAR(DATAPEDIDO) AS AN0, 0 AS JAN, 0 AS FEV, 0 AS MAR, 0 AS ABR, 0 AS MAI, SUM(VALORTOTAL) AS JUN, 
0 AS JUL, 0 AS AGO, 0 AS 'SET', 0 AS 'OUT', 0 AS NOV, 0 AS DEZ, SUM(VALORTOTAL) AS TOTAL
FROM PEDIDO
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = PEDIDO.FKCLIENTE
WHERE MONTH(DATAPEDIDO) = 6
GROUP BY NOME, YEAR(DATAPEDIDO)
UNION
SELECT NOME, YEAR(DATAPEDIDO) AS AN0, 0 AS JAN, 0 AS FEV, 0 AS MAR, 0 AS ABR, 0 AS MAI, 0 AS JUN, 
SUM(VALORTOTAL) AS JUL, 0 AS AGO, 0 AS 'SET', 0 AS 'OUT', 0 AS NOV, 0 AS DEZ, SUM(VALORTOTAL) AS TOTAL
FROM PEDIDO
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = PEDIDO.FKCLIENTE
WHERE MONTH(DATAPEDIDO) = 7
GROUP BY NOME, YEAR(DATAPEDIDO)
UNION
SELECT NOME, YEAR(DATAPEDIDO) AS AN0, 0 AS JAN, 0 AS FEV, 0 AS MAR, 0 AS ABR, 0 AS MAI, 0 AS JUN, 
0 AS JUL, SUM(VALORTOTAL) AS AGO, 0 AS 'SET', 0 AS 'OUT', 0 AS NOV, 0 AS DEZ, SUM(VALORTOTAL) AS TOTAL
FROM PEDIDO
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = PEDIDO.FKCLIENTE
WHERE MONTH(DATAPEDIDO) = 8
GROUP BY NOME, YEAR(DATAPEDIDO)
UNION
SELECT NOME, YEAR(DATAPEDIDO) AS AN0, 0 AS JAN, 0 AS FEV, 0 AS MAR, 0 AS ABR, 0 AS MAI, 0 AS JUN, 
0 AS JUL, 0 AS AGO, SUM(VALORTOTAL) AS 'SET', 0 AS 'OUT', 0 AS NOV, 0 AS DEZ, SUM(VALORTOTAL) AS TOTAL
FROM PEDIDO
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = PEDIDO.FKCLIENTE
WHERE MONTH(DATAPEDIDO) = 9
GROUP BY NOME, YEAR(DATAPEDIDO)
UNION
SELECT NOME, YEAR(DATAPEDIDO) AS AN0, 0 AS JAN, 0 AS FEV, 0 AS MAR, 0 AS ABR, 0 AS MAI, 0 AS JUN, 
0 AS JUL, 0 AS AGO, 0 AS 'SET', SUM(VALORTOTAL) AS 'OUT', 0 AS NOV, 0 AS DEZ, SUM(VALORTOTAL) AS TOTAL
FROM PEDIDO
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = PEDIDO.FKCLIENTE
WHERE MONTH(DATAPEDIDO) = 10
GROUP BY NOME, YEAR(DATAPEDIDO)
UNION
SELECT NOME, YEAR(DATAPEDIDO) AS AN0, 0 AS JAN, 0 AS FEV, 0 AS MAR, 0 AS ABR, 0 AS MAI, 0 AS JUN, 
0 AS JUL, 0 AS AGO, 0 AS 'SET', 0 AS 'OUT', SUM(VALORTOTAL) AS NOV, 0 AS DEZ, SUM(VALORTOTAL) AS TOTAL
FROM PEDIDO
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = PEDIDO.FKCLIENTE
WHERE MONTH(DATAPEDIDO) = 11
GROUP BY NOME, YEAR(DATAPEDIDO)
UNION
SELECT NOME, YEAR(DATAPEDIDO) AS AN0, 0 AS JAN, 0 AS FEV, 0 AS MAR, 0 AS ABR, 0 AS MAI, 0 AS JUN, 
0 AS JUL, 0 AS AGO, 0 AS 'SET', 0 AS 'OUT', 0 AS NOV, SUM(VALORTOTAL) AS DEZ, SUM(VALORTOTAL) AS TOTAL
FROM PEDIDO
INNER JOIN CLIENTE ON CLIENTE.IDCLIENTE = PEDIDO.FKCLIENTE
WHERE MONTH(DATAPEDIDO) = 12
GROUP BY NOME, YEAR(DATAPEDIDO);

SELECT * FROM SOMATOTAL;

SELECT NOME, SUM(JAN) AS JAN, SUM(FEV) AS FEV, SUM(MAR) AS MAR, SUM(ABR) AS ABR, SUM(MAI) AS MAI, SUM(JUN) AS JUN,
SUM(JUL) AS JUL, SUM(AGO) AS AGO, SUM('SET') AS 'SET', SUM('OUT') AS 'OUT', SUM(NOV) AS NOV, SUM(DEZ) AS DEZ
FROM SOMATOTAL
WHERE ANO = 2020
GROUP BY NOME
ORDER BY NOME;
