USE EmpresaPedidos;

-- ATIVIDADE (11/10)

SELECT * FROM Cliente;
Select * from Pedido;

-- 1) Liste o valor total de pedidos, por cliente da região sul, realizados nos últimos 2 anos
SELECT SUM(P.VALORTOTAL) AS VALOR_TOTAL,
C.NOME AS CLIENTE
FROM Pedido AS P
INNER JOIN Cliente AS C ON P.FKCLIENTE = C.IDCLIENTE
INNER JOIN Enderecos AS E ON C.IDCLIENTE = E.FKCIDADE
INNER JOIN Cidade AS CI ON CI.IDCIDADE = E.FKCIDADE
WHERE YEAR(P.DATAPEDIDO) IN(2023, 2022)
AND CI.SIGLAESTADO IN('PR', 'RS', 'SC')
GROUP BY C.NOME;

-- 2) Liste os 10 produtos mais vendidos no último ano
SELECT P.NOMEPRODUTO, (COUNT(PI.IDITEM) * PI.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM PedidoItens AS PI
INNER JOIN Produto AS P ON P.IDPRODUTO = PI.FKPRODUTO
INNER JOIN Pedido AS PE ON PE.IDPEDIDO = PI.FKPEDIDO
WHERE YEAR(PE.DATAPEDIDO) = 2022
GROUP BY P.NOMEPRODUTO
ORDER BY QUANTIDADE_TOTAL DESC
LIMIT 10;

-- 3) Liste o valor total de pedidos, por cliente, mês a mês no ano de 2021, no formato a seguir. 
-- Utilize o UNION para juntar os valores de cada mês em um único SELECT.
SELECT C.NOME AS CLIENTE, MONTH(P.DATAPEDIDO) AS MES, SUM(P.VALORTOTAL) AS VALOR_TOTAL
FROM Cliente AS C
INNER JOIN Pedido AS P ON P.FKCLIENTE = C.IDCLIENTE
WHERE YEAR(P.DATAPEDIDO) = 2021
GROUP BY C.NOME, MONTH(P.DATAPEDIDO)
ORDER BY MES;
