CREATE DATABASE IF NOT EXISTS TESTE_ALTER;
USE TESTE_ALTER;

/*
	ALTER:
		ADD (COLUMN, PRIMARY KEY, FOREIGN KEY)
        CHANGE
        DROP
*/

CREATE TABLE IF NOT EXISTS TESTE (
	ID INT AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    RG VARCHAR(10) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    PRIMARY KEY(ID),
    UNIQUE(RG), -- TORNO O RG ÚNICO, SÓ PODE TER 1
    CHECK(SEXO = 'F') -- SÓ VOU INSERIR SE O SEXO FOR FEMININO
);

ALTER TABLE TESTE
CHANGE COLUMN NOME -- QUAL COLUNA QUERO ALTERAR
NOME VARCHAR(50) NOT NULL; -- REPITO O NOME, PORQUE PODERIA TROCÁ-LO, E COLOCO O RESTANTE DAS CONF

ALTER TABLE TESTE DROP COLUMN NOME; -- DELETA A COLUNA
ALTER TABLE TESTE ADD COLUMN CPF VARCHAR(14); -- ADICIONA A COLUNA