/* LOGICO_FINAL_: */


DROP DATABASE IF EXISTS ATHLANTIC;
CREATE DATABASE ATHLANTIC;
USE ATHLANTIC;

CREATE TABLE USUARIOS (
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USU_SENHA VARCHAR(20),
    USU_INSTITUICAO_ENSINO VARCHAR(80),
    USU_ATIVO TINYINT,
    USU_FOTO VARCHAR(255),
    USU_NOME VARCHAR(80),
    USU_DESCRICAO VARCHAR(150),
    USU_EMAIL VARCHAR(255),
    FK_ATLETICAS_ATL_ID INTEGER,
    FK_EQUIPES_EQP_ID INTEGER
);

CREATE TABLE ATLETICAS (
    ATL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ATL_NOME VARCHAR(80),
    ATL_LEMA VARCHAR(50),
    ATL_ATIVO TINYINT,
    ATL_DESCRICAO VARCHAR(200),
    ATL_LOGO longblob,
    ATL_INSTITUICAO_ENSINO VARCHAR(255),
    FK_ADMINISTRADORES_ADM_ID INTEGER
);

CREATE TABLE NOTIFICACOES (
    NOT_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOT_TIPO VARCHAR(30),
    NOT_TITULO VARCHAR(50),
    NOT_DESCRICAO VARCHAR(100),
    FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE PAGAMENTOS (
    PAG_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PAG_VALOR_PAGO DECIMAL(8,2),
    PAG_DATA DATE,
    PAG_CONDICAO ENUM("CANCELADO", "PENDENTE","PAGO"),
    FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE CARGOS (
    CAR_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CAR_NOME VARCHAR(80)
);

CREATE TABLE FUNCIONALIDADES (
    FUN_NOME VARCHAR(50),
    FUN_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE VOTACOES (
    VOT_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VOT_PRAZO DATE,
    FK_CHAMADOS_CHA_ID INTEGER
);

CREATE TABLE CHAMADOS (
    CHA_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CHA_NOME VARCHAR(50),
    CHA_DESCRICAO VARCHAR(150)
);

CREATE TABLE ADMINISTRADORES (
    ADM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ADM_NOME VARCHAR(80),
    ADM_SENHA VARCHAR(20),
    ADM_EMAIL VARCHAR(255)
);

CREATE TABLE REQUISICOES_ATLETICAS (
    REQ_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    REQ_NOME_USUARIO VARCHAR(50),
    REQ_INSTITUICAO_ENSINO VARCHAR(80),
    REQ_SENHA VARCHAR(20),
    REQ_EMAIL VARCHAR(100),
    REQ_CONFIRMAR_SENHA VARCHAR(20),
    REQ_NOME_ATLETICA VARCHAR(50),
    REQ_LOGO_ATLETICA VARCHAR(255),
    REQ_DESCRICAO_ATLETICA VARCHAR(100),
    FK_ADMINISTRADORES_ADM_ID INTEGER
);

CREATE TABLE PLANOS (
    PLA_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PLA_CUSTO DECIMAL(8,2),
    PLA_VANTAGEM VARCHAR(200),
    PLA_NOME VARCHAR(50)
);

CREATE TABLE DENUNCIAS (
    DNC_DESCRICAO VARCHAR(255),
    DNC_TIPO_DENUNCIA INTEGER,
    DNC_FK_ID_COMENTARIO_POSTAGEM INTEGER,
    DNC_MOTIVO INTEGER,
    DNC_DATA DATE,
    DNC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE COMENTARIOS (
    CMT_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CMT_TIPO_POSTAGEM INTEGER,
    CMT_FK_ID_POSTAGEM INTEGER,
    CMT_CURTIDAS INTEGER,
    CMT_TEXTO VARCHAR(255),
    FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE POSTAGENS_GERAL (
    PST_DESCRICAO VARCHAR(255),
    PST_CURTIDAS INTEGER,
    PST_DATA DATE,
    PST_IMAGEM LONGBLOB,
    PST_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE POSTAGENS_EVENTOS (
    PSE_ID INTEGER,
    PSE_TITULO VARCHAR(25),
    FK_POSTAGENS_GERAL_PST_ID INTEGER,
    FK_EVENTOS_SOCIAIS_EVS_ID INTEGER,
    FK_EVENTOS_ESPORTIVOS_EVE_ID INTEGER,
    PRIMARY KEY (PSE_ID, FK_POSTAGENS_GERAL_PST_ID)
);

CREATE TABLE POSTAGENS_PRODUTOS (
    PSP_ID INTEGER,
    PSP_TITULO VARCHAR(25),
    FK_POSTAGENS_GERAL_PST_ID INTEGER,
    FK_PRODUTOS_PRO_ID INTEGER,
    PRIMARY KEY (PSP_ID, FK_POSTAGENS_GERAL_PST_ID)
);

CREATE TABLE PRODUTOS (
    PRO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRO_NOME VARCHAR(60),
    PRO_DESCRICAO VARCHAR(255),
    PRO_QUANTIDADE INTEGER,
    PRO_STATUS VARCHAR(30),
    PRO_EXCLUSIVIDADE TINYINT,
    PRO_EXCLUIDO TINYINT,
    FK_FORNECEDORES_FOR_ID INTEGER
);

CREATE TABLE FORNECEDORES (
    FOR_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FOR_NOME VARCHAR(60),
    FOR_DESCRICAO VARCHAR(255),
    FOR_CONTATO VARCHAR(100),
    FOR_ENDERECO VARCHAR(100),
    FOR_ATIVO TINYINT
);

CREATE TABLE LOTES_PRODUTOS (
    LOP_QUANTIDADE_PENDENTE INTEGER,
    LOP_PRECO_PRODUTO DECIMAL(8,2),
    LOP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LOP_QUANTIDADE_DISPONIVEL INTEGER,
    LOP_VENDAMINIMA INTEGER,
    FK_PRODUTOS_PRO_ID INTEGER
);

CREATE TABLE ITEMS_COMPRAS (
    ITC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ITS_QUANTIDADE INTEGER,
    FK_COMPRAS_CMP_ID INTEGER,
    FK_LOTES_PRODUTOS_LOP_ID INTEGER
);

CREATE TABLE COMPRAS (
    CMP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CMP_STATUS ENUM('FINALIZADO', 'PENDENTE', 'CANCELADO'),
    CMP_DESCONTO TINYINT,
    CMP_VALOR_DESCONTO DECIMAL(8,2),
    CMP_DATA DATE,
    FK_USUARIOS_USU_ID INTEGER
);

CREATE TABLE COMPRAS_INGRESSOS (
    CPI_DATA_COMPRA INTEGER,
    CPI_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CPI_STATUS ENUM('FINALIZADO', 'PENDENTE', 'CANCELADO'),
    FK_USUARIOS_USU_ID INTEGER,
    FK_LOTES_INGRESSOS_LOI_ID INTEGER
);

CREATE TABLE INGRESSOS (
    ING_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ING_NUMEROINGRESSO INTEGER,
    FK_EVENTOS_SOCIAIS_EVS_ID INTEGER,
    FK_EVENTOS_ESPORTIVOS_EVE_ID INTEGER
);

CREATE TABLE LOTES_INGRESSOS (
    LOI_QUANTIDADE_PENDENTE INTEGER,
    LOI_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LOI_QUANTIDADE_DISPONIVEL INTEGER,
    LOI_VALOR DECIMAL(8,2),
    LOI_VENDAMINIMA INTEGER,
    FK_INGRESSOS_ING_ID INTEGER
);

CREATE TABLE DESPESAS (
    DEP_NOME VARCHAR(120),
    DEP_DESCRICAO VARCHAR(250),
    DEP_ID_ENTIDADE INTEGER,
    DEP_DATA DATE,
    DEP_VALOR DOUBLE,
    DEP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DEP_TIPO ENUM('EVENTO', 'PRODUTO'),
    DEP_FORMA_PAGAMENTO ENUM('DEBITO', 'CREDITO', 'PIX', 'DINHEIRO'),
    FK_ATLETICAS_ATL_ID INTEGER
);

CREATE TABLE ENTRADAS (
    ENT_DESCRICAO VARCHAR(7),
    ENT_DATA DATE,
    ENT_VALOR DOUBLE,
    ENT_NOME VARCHAR(100),
    ENT_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ATLETICAS_ATL_ID INTEGER
);

CREATE TABLE PATROCINIOS (
    PAT_IMAGEM longblob,
    PAT_DATAFINAL DATE,
    PAT_DATAINICIAL DATE,
    PAT_VALOR DOUBLE,
    PAT_NOME VARCHAR(255),
    PAT_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PAT_DESCRICAO VARCHAR(255),
    FK_ATLETICAS_ATL_ID INTEGER,
    FK_PATROCINADORES_PTS_ID INTEGER
);

CREATE TABLE PATROCINADORES (
    PTS_TELEFONE VARCHAR(18),
    PTS_SITE_URL VARCHAR(255),
    PTS_CPF_CNPJ VARCHAR(255),
    PTS_PESSOA_FISICA TINYINT,
    PTS_DATA_CADASTRO DATE,
    PTS_NOME VARCHAR(60),
    PTS_EMAIL VARCHAR(255),
    PTS_ATIVO BOOLEAN,
    PTS_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE JOGOS (
    JOG_HORARIO DATETIME,
    JOG_EQPB_RESULTADO_FINAL INTEGER,
    JOG_EQPA_RESULTADO_FINAL INTEGER,
    JOG_DIA DATE,
    JOG_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    JOG_LOCAL VARCHAR(50),
    FK_CAMPEONATOS_MODALIDADES_CMM_ID INTEGER
);

CREATE TABLE AUTORIDADES (
    ATD_MODALIDADE_ESPORTIVA INTEGER,
    ATD_CERTIFICACAO VARCHAR(30),
    ATD_TELEFONE VARCHAR(15),
    ATD_IDENTIFICACAO_FISCAL VARCHAR(20),
    ATD_NOME VARCHAR(50),
    ATD_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ATD_EMAIL VARCHAR(50),
    ATD_FUNCAO VARCHAR(30)
);

CREATE TABLE CAMPEONATOS_MODALIDADES (
    CMM_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_MODALIDADES_ESPORTIVAS_MDE_ID INTEGER,
    FK_EVENTOS_ESPORTIVOS_EVE_ID INTEGER
);

CREATE TABLE MODALIDADES_ESPORTIVAS (
    MDE_TIPO_DE_ESPORTE INTEGER,
    MDE_NOME VARCHAR(50),
    MDE_GENERO INTEGER,
    MDE_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE PROVAS (
    PRO_DIA DATE,
    PRO_HORARIO DATETIME,
    PRO_LOCAL VARCHAR(50),
    PRO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CAMPEONATOS_MODALIDADES_CMM_ID INTEGER
);

CREATE TABLE EQUIPES (
    EQP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EQP_TREINADOR VARCHAR(50),
    FK_ATLETICAS_ATL_ID INTEGER,
    FK_MODALIDADES_ESPORTIVAS_MDE_ID INTEGER,
    FK_EQUIPES_ATLETAS_ETL_ID INTEGER
);

CREATE TABLE EVENTOS_SOCIAIS (
    EVS_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EVE_PRECO DOUBLE,
    EVE_DATAEVENTO DATE,
    EVE_TIPOENTRADA BOOLEAN,
    EVE_DESCRICAO VARCHAR(255),
    EVE_IMAGEMPROMOCIONAL longblob,
    EVE_NOME VARCHAR(60),
    EVE_ENDERECOEVENTO VARCHAR(120),
    FK_ATLETICAS_ATL_ID INTEGER
);

CREATE TABLE EVENTOS_ESPORTIVOS (
    EVE_ID INTEGER  AUTO_INCREMENT PRIMARY KEY,
    EVE_PRECO DOUBLE,
    EVE_DATAEVENTO DATE,
    EVE_TIPOENTRADA BOOLEAN,
    EVE_DESCRICAO VARCHAR(255),
    EVE_IMAGEMPROMOCIONAL longblob,
    EVE_NOME VARCHAR(60),
    EVE_ENDERECOEVENTO VARCHAR(120),
    FK_ATLETICAS_ATL_ID INTEGER
);

CREATE TABLE PRODUTOS_IMAGENS (
    PDI_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PDI_IMAGEM longblob,
    FK_PRODUTOS_PRO_ID INTEGER
);

CREATE TABLE USUARIOS_CARGOS (
    FK_CARGOS_CAR_ID INTEGER,
    FK_USUARIOS_USU_ID INTEGER,
    USC_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE CARGOS_FUNCIONALIDADES (
    FK_CARGOS_CAR_ID INTEGER,
    FK_FUNCIONALIDADES_FUN_ID INTEGER,
    PRI_POSSUI TINYINT,
    PRI_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE VOTACAOES_USUARIOS (
    FK_USUARIOS_USU_ID INTEGER,
    FK_VOTACOES_VOT_ID INTEGER,
    VTS_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VTS_DATA DATE,
    VTS_STATUS TINYINT
);

CREATE TABLE USUARIOS_CHAMADOS (
    FK_USUARIOS_USU_ID INTEGER,
    FK_CHAMADOS_CHA_ID INTEGER,
    USC_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE PLANOS_ATLETICA (
    FK_ATLETICAS_ATL_ID INTEGER,
    FK_PLANOS_PLA_ID INTEGER,
    PLA_ID INTEGER  AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE FORNECEDORES_EVENTOS (
    FK_FORNECEDORES_FOR_ID INTEGER,
    FK_EVENTOS_SOCIAIS_EVS_ID INTEGER,
    FK_EVENTOS_ESPORTIVOS_EVE_ID INTEGER,
    FOE_ID INTEGER  AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE PATROCINADORES_EVENTOS (
    FK_EVENTOS_SOCIAIS_EVS_ID INTEGER,
    FK_EVENTOS_ESPORTIVOS_EVE_ID INTEGER,
    FK_PATROCINADORES_PTS_ID INTEGER,
    PTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE ESTATISTICAS_JOGO_ATLETA (
    FK_JOGOS_JOG_ID INTEGER,
    FK_USUARIOS_USU_ID INTEGER,
    EJA_TEMPO_QUARTO_SET DATETIME,
    EJA_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EJA_TIPO_ESTATISTICAS INTEGER,
    EJA_TEMPO_NO_JOGO DATETIME,
    EJA_VALOR INTEGER
);

CREATE TABLE EQUIPES_JOGOS (
    FK_EQUIPES_EQP_ID INTEGER,
    FK_JOGOS_JOG_ID INTEGER,
    EJQ_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE ARBITRO_JOGOS (
    FK_AUTORIDADES_ATD_ID INTEGER,
    FK_JOGOS_JOG_ID INTEGER,
    ABJ_FUNCAO INTEGER,
    ABJ_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE ARBITRO_PROVAS (
    FK_AUTORIDADES_ATD_ID INTEGER,
    FK_PROVAS_PRO_ID INTEGER,
    ABP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ABP_FUNCAO INTEGER
);

CREATE TABLE ESTATISTICAS_PROVAS_USUARIOS (
    FK_PROVAS_PRO_ID INTEGER,
    FK_USUARIOS_USU_ID INTEGER,
    EPA_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EJA_TIPO_ESTATISTICAS INTEGER,
    EJA_VALOR INTEGER,
    EJA_TENTATIVAS INTEGER
);

CREATE TABLE USUARIOS_INSCRITOS (
    FK_PROVAS_PRO_ID INTEGER,
    FK_USUARIOS_USU_ID INTEGER,
    USI_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE USUARIOS_PLANOS (
    FK_PLANOS_PLA_ID INTEGER,
    FK_USUARIOS_USU_ID INTEGER,
    USP_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE EQUIPES_PARTICIPANTES (
    FK_EQUIPES_EQP_ID INTEGER,
    FK_CAMPEONATOS_MODALIDADES_CMM_ID INTEGER,
    EPA_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE REQUISICOES_USUARIOS (
    REQ_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    REQ_NOME_USUARIO VARCHAR(50),
    REQ_SENHA VARCHAR(20),
    REQ_EMAIL VARCHAR(100),
    REQ_CONFIRMAR_SENHA VARCHAR(20),
    FK_ATLETICAS_ATL_ID INTEGER
);

CREATE TABLE AUTORIDADES_MODALIDADES (
    ATE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_MODADLIDADE_ESPORTIVA_MDE_ID INTEGER
);

CREATE TABLE EQUIPES_ATLETAS (
    ETL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_USUARIOS_USU_ID INTEGER
);
 
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_2
    FOREIGN KEY (FK_ATLETICAS_ATL_ID)
    REFERENCES ATLETICAS (ATL_ID)
    ON DELETE CASCADE;
 
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_3
    FOREIGN KEY (FK_EQUIPES_EQP_ID)
    REFERENCES EQUIPES (EQP_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ATLETICAS ADD CONSTRAINT FK_ATLETICAS_2
    FOREIGN KEY (FK_ADMINISTRADORES_ADM_ID)
    REFERENCES ADMINISTRADORES (ADM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE NOTIFICACOES ADD CONSTRAINT FK_NOTIFICACOES_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PAGAMENTOS ADD CONSTRAINT FK_PAGAMENTOS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE VOTACOES ADD CONSTRAINT FK_VOTACOES_2
    FOREIGN KEY (FK_CHAMADOS_CHA_ID)
    REFERENCES CHAMADOS (CHA_ID)
    ON DELETE CASCADE;
 
ALTER TABLE REQUISICOES_ATLETICAS ADD CONSTRAINT FK_REQUISICOES_ATLETICAS_2
    FOREIGN KEY (FK_ADMINISTRADORES_ADM_ID)
    REFERENCES ADMINISTRADORES (ADM_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE DENUNCIAS ADD CONSTRAINT FK_DENUNCIAS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE COMENTARIOS ADD CONSTRAINT FK_COMENTARIOS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE POSTAGENS_GERAL ADD CONSTRAINT FK_POSTAGENS_GERAL_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE POSTAGENS_EVENTOS ADD CONSTRAINT FK_POSTAGENS_EVENTOS_2
    FOREIGN KEY (FK_POSTAGENS_GERAL_PST_ID)
    REFERENCES POSTAGENS_GERAL (PST_ID)
    ON DELETE CASCADE;
 
ALTER TABLE POSTAGENS_EVENTOS ADD CONSTRAINT FK_POSTAGENS_EVENTOS_3
    FOREIGN KEY (FK_EVENTOS_SOCIAIS_EVS_ID)
    REFERENCES EVENTOS_SOCIAIS (EVS_ID)
    ON DELETE CASCADE;
 
ALTER TABLE POSTAGENS_EVENTOS ADD CONSTRAINT FK_POSTAGENS_EVENTOS_4
    FOREIGN KEY (FK_EVENTOS_ESPORTIVOS_EVE_ID)
    REFERENCES EVENTOS_ESPORTIVOS (EVE_ID)
    ON DELETE CASCADE;
 
ALTER TABLE POSTAGENS_PRODUTOS ADD CONSTRAINT FK_POSTAGENS_PRODUTOS_2
    FOREIGN KEY (FK_POSTAGENS_GERAL_PST_ID)
    REFERENCES POSTAGENS_GERAL (PST_ID)
    ON DELETE CASCADE;
 
ALTER TABLE POSTAGENS_PRODUTOS ADD CONSTRAINT FK_POSTAGENS_PRODUTOS_3
    FOREIGN KEY (FK_PRODUTOS_PRO_ID)
    REFERENCES PRODUTOS (PRO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_2
    FOREIGN KEY (FK_FORNECEDORES_FOR_ID)
    REFERENCES FORNECEDORES (FOR_ID)
    ON DELETE CASCADE;
 
ALTER TABLE LOTES_PRODUTOS ADD CONSTRAINT FK_LOTES_PRODUTOS_2
    FOREIGN KEY (FK_PRODUTOS_PRO_ID)
    REFERENCES PRODUTOS (PRO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ITEMS_COMPRAS ADD CONSTRAINT FK_ITEMS_COMPRAS_2
    FOREIGN KEY (FK_COMPRAS_CMP_ID)
    REFERENCES COMPRAS (CMP_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE ITEMS_COMPRAS ADD CONSTRAINT FK_ITEMS_COMPRAS_3
    FOREIGN KEY (FK_LOTES_PRODUTOS_LOP_ID)
    REFERENCES LOTES_PRODUTOS (LOP_ID)
    ON DELETE CASCADE;
 
ALTER TABLE COMPRAS ADD CONSTRAINT FK_COMPRAS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE COMPRAS_INGRESSOS ADD CONSTRAINT FK_COMPRAS_INGRESSOS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE COMPRAS_INGRESSOS ADD CONSTRAINT FK_COMPRAS_INGRESSOS_3
    FOREIGN KEY (FK_LOTES_INGRESSOS_LOI_ID)
    REFERENCES LOTES_INGRESSOS (LOI_ID)
    ON DELETE CASCADE;
 
ALTER TABLE INGRESSOS ADD CONSTRAINT FK_INGRESSOS_2
    FOREIGN KEY (FK_EVENTOS_SOCIAIS_EVS_ID)
    REFERENCES EVENTOS_SOCIAIS (EVS_ID)
    ON DELETE CASCADE;
 
ALTER TABLE INGRESSOS ADD CONSTRAINT FK_INGRESSOS_3
    FOREIGN KEY (FK_EVENTOS_ESPORTIVOS_EVE_ID)
    REFERENCES EVENTOS_ESPORTIVOS (EVE_ID)
    ON DELETE CASCADE;
 
ALTER TABLE LOTES_INGRESSOS ADD CONSTRAINT FK_LOTES_INGRESSOS_2
    FOREIGN KEY (FK_INGRESSOS_ING_ID)
    REFERENCES INGRESSOS (ING_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE DESPESAS ADD CONSTRAINT FK_DESPESAS_2
    FOREIGN KEY (FK_ATLETICAS_ATL_ID)
    REFERENCES ATLETICAS (ATL_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ENTRADAS ADD CONSTRAINT FK_ENTRADAS_2
    FOREIGN KEY (FK_ATLETICAS_ATL_ID)
    REFERENCES ATLETICAS (ATL_ID)
    ON DELETE SET NULL;
 
ALTER TABLE PATROCINIOS ADD CONSTRAINT FK_PATROCINIOS_2
    FOREIGN KEY (FK_ATLETICAS_ATL_ID)
    REFERENCES ATLETICAS (ATL_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PATROCINIOS ADD CONSTRAINT FK_PATROCINIOS_3
    FOREIGN KEY (FK_PATROCINADORES_PTS_ID)
    REFERENCES PATROCINADORES (PTS_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE JOGOS ADD CONSTRAINT FK_JOGOS_2
    FOREIGN KEY (FK_CAMPEONATOS_MODALIDADES_CMM_ID)
    REFERENCES CAMPEONATOS_MODALIDADES (CMM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE AUTORIDADES ADD CONSTRAINT FK_AUTORIDADES_2
    FOREIGN KEY (ATD_MODALIDADE_ESPORTIVA)
    REFERENCES AUTORIDADES_MODALIDADES (ATE_ID);
 
ALTER TABLE CAMPEONATOS_MODALIDADES ADD CONSTRAINT FK_CAMPEONATOS_MODALIDADES_2
    FOREIGN KEY (FK_MODALIDADES_ESPORTIVAS_MDE_ID)
    REFERENCES MODALIDADES_ESPORTIVAS (MDE_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CAMPEONATOS_MODALIDADES ADD CONSTRAINT FK_CAMPEONATOS_MODALIDADES_3
    FOREIGN KEY (FK_EVENTOS_ESPORTIVOS_EVE_ID)
    REFERENCES EVENTOS_ESPORTIVOS (EVE_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PROVAS ADD CONSTRAINT FK_PROVAS_2
    FOREIGN KEY (FK_CAMPEONATOS_MODALIDADES_CMM_ID)
    REFERENCES CAMPEONATOS_MODALIDADES (CMM_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EQUIPES ADD CONSTRAINT FK_EQUIPES_2
    FOREIGN KEY (FK_ATLETICAS_ATL_ID)
    REFERENCES ATLETICAS (ATL_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EQUIPES ADD CONSTRAINT FK_EQUIPES_3
    FOREIGN KEY (FK_MODALIDADES_ESPORTIVAS_MDE_ID)
    REFERENCES MODALIDADES_ESPORTIVAS (MDE_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EQUIPES ADD CONSTRAINT FK_EQUIPES_4
    FOREIGN KEY (FK_EQUIPES_ATLETAS_ETL_ID)
    REFERENCES EQUIPES_ATLETAS (ETL_ID)
    ON DELETE SET NULL;
 
ALTER TABLE EVENTOS_SOCIAIS ADD CONSTRAINT FK_EVENTOS_SOCIAIS_2
    FOREIGN KEY (FK_ATLETICAS_ATL_ID)
    REFERENCES ATLETICAS (ATL_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EVENTOS_ESPORTIVOS ADD CONSTRAINT FK_EVENTOS_ESPORTIVOS_2
    FOREIGN KEY (FK_ATLETICAS_ATL_ID)
    REFERENCES ATLETICAS (ATL_ID)
    ON DELETE CASCADE;
 
ALTER TABLE PRODUTOS_IMAGENS ADD CONSTRAINT FK_PRODUTOS_IMAGENS_2
    FOREIGN KEY (FK_PRODUTOS_PRO_ID)
    REFERENCES PRODUTOS (PRO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE USUARIOS_CARGOS ADD CONSTRAINT FK_USUARIOS_CARGOS_2
    FOREIGN KEY (FK_CARGOS_CAR_ID)
    REFERENCES CARGOS (CAR_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE USUARIOS_CARGOS ADD CONSTRAINT FK_USUARIOS_CARGOS_3
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE SET NULL;
 
ALTER TABLE CARGOS_FUNCIONALIDADES ADD CONSTRAINT FK_CARGOS_FUNCIONALIDADES_2
    FOREIGN KEY (FK_CARGOS_CAR_ID)
    REFERENCES CARGOS (CAR_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE CARGOS_FUNCIONALIDADES ADD CONSTRAINT FK_CARGOS_FUNCIONALIDADES_3
    FOREIGN KEY (FK_FUNCIONALIDADES_FUN_ID)
    REFERENCES FUNCIONALIDADES (FUN_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE VOTACAOES_USUARIOS ADD CONSTRAINT FK_VOTACAOES_USUARIOS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE SET NULL;
 
ALTER TABLE VOTACAOES_USUARIOS ADD CONSTRAINT FK_VOTACAOES_USUARIOS_3
    FOREIGN KEY (FK_VOTACOES_VOT_ID)
    REFERENCES VOTACOES (VOT_ID)
    ON DELETE SET NULL;
 
ALTER TABLE USUARIOS_CHAMADOS ADD CONSTRAINT FK_USUARIOS_CHAMADOS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE SET NULL;
 
ALTER TABLE USUARIOS_CHAMADOS ADD CONSTRAINT FK_USUARIOS_CHAMADOS_3
    FOREIGN KEY (FK_CHAMADOS_CHA_ID)
    REFERENCES CHAMADOS (CHA_ID)
    ON DELETE SET NULL;
 
ALTER TABLE PLANOS_ATLETICA ADD CONSTRAINT FK_PLANOS_ATLETICA_2
    FOREIGN KEY (FK_ATLETICAS_ATL_ID)
    REFERENCES ATLETICAS (ATL_ID)
    ON DELETE SET NULL;
 
ALTER TABLE PLANOS_ATLETICA ADD CONSTRAINT FK_PLANOS_ATLETICA_3
    FOREIGN KEY (FK_PLANOS_PLA_ID)
    REFERENCES PLANOS (PLA_ID)
    ON DELETE SET NULL;
 
ALTER TABLE FORNECEDORES_EVENTOS ADD CONSTRAINT FK_FORNECEDORES_EVENTOS_2
    FOREIGN KEY (FK_FORNECEDORES_FOR_ID)
    REFERENCES FORNECEDORES (FOR_ID)
    ON DELETE SET NULL;
 
ALTER TABLE FORNECEDORES_EVENTOS ADD CONSTRAINT FK_FORNECEDORES_EVENTOS_3
    FOREIGN KEY (FK_EVENTOS_SOCIAIS_EVS_ID)
    REFERENCES EVENTOS_SOCIAIS (EVS_ID)
    ON DELETE SET NULL;
 
ALTER TABLE FORNECEDORES_EVENTOS ADD CONSTRAINT FK_FORNECEDORES_EVENTOS_4
    FOREIGN KEY (FK_EVENTOS_ESPORTIVOS_EVE_ID)
    REFERENCES EVENTOS_ESPORTIVOS (EVE_ID)
    ON DELETE SET NULL;
 
ALTER TABLE PATROCINADORES_EVENTOS ADD CONSTRAINT FK_PATROCINADORES_EVENTOS_2
    FOREIGN KEY (FK_EVENTOS_SOCIAIS_EVS_ID)
    REFERENCES EVENTOS_SOCIAIS (EVS_ID)
    ON DELETE SET NULL;
 
ALTER TABLE PATROCINADORES_EVENTOS ADD CONSTRAINT FK_PATROCINADORES_EVENTOS_3
    FOREIGN KEY (FK_EVENTOS_ESPORTIVOS_EVE_ID)
    REFERENCES EVENTOS_ESPORTIVOS (EVE_ID)
    ON DELETE SET NULL;
 
ALTER TABLE PATROCINADORES_EVENTOS ADD CONSTRAINT FK_PATROCINADORES_EVENTOS_4
    FOREIGN KEY (FK_PATROCINADORES_PTS_ID)
    REFERENCES PATROCINADORES (PTS_ID)
    ON DELETE SET NULL;
 
ALTER TABLE ESTATISTICAS_JOGO_ATLETA ADD CONSTRAINT FK_ESTATISTICAS_JOGO_ATLETA_2
    FOREIGN KEY (FK_JOGOS_JOG_ID)
    REFERENCES JOGOS (JOG_ID)
    ON DELETE SET NULL;
 
ALTER TABLE ESTATISTICAS_JOGO_ATLETA ADD CONSTRAINT FK_ESTATISTICAS_JOGO_ATLETA_3
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE SET NULL;
 
ALTER TABLE EQUIPES_JOGOS ADD CONSTRAINT FK_EQUIPES_JOGOS_2
    FOREIGN KEY (FK_EQUIPES_EQP_ID)
    REFERENCES EQUIPES (EQP_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE EQUIPES_JOGOS ADD CONSTRAINT FK_EQUIPES_JOGOS_3
    FOREIGN KEY (FK_JOGOS_JOG_ID)
    REFERENCES JOGOS (JOG_ID)
    ON DELETE SET NULL;
 
ALTER TABLE ARBITRO_JOGOS ADD CONSTRAINT FK_ARBITRO_JOGOS_2
    FOREIGN KEY (FK_AUTORIDADES_ATD_ID)
    REFERENCES AUTORIDADES (ATD_ID)
    ON DELETE SET NULL;
 
ALTER TABLE ARBITRO_JOGOS ADD CONSTRAINT FK_ARBITRO_JOGOS_3
    FOREIGN KEY (FK_JOGOS_JOG_ID)
    REFERENCES JOGOS (JOG_ID)
    ON DELETE SET NULL;
 
ALTER TABLE ARBITRO_PROVAS ADD CONSTRAINT FK_ARBITRO_PROVAS_2
    FOREIGN KEY (FK_AUTORIDADES_ATD_ID)
    REFERENCES AUTORIDADES (ATD_ID)
    ON DELETE SET NULL;
 
ALTER TABLE ARBITRO_PROVAS ADD CONSTRAINT FK_ARBITRO_PROVAS_3
    FOREIGN KEY (FK_PROVAS_PRO_ID)
    REFERENCES PROVAS (PRO_ID)
    ON DELETE SET NULL;
 
ALTER TABLE ESTATISTICAS_PROVAS_USUARIOS ADD CONSTRAINT FK_ESTATISTICAS_PROVAS_USUARIOS_2
    FOREIGN KEY (FK_PROVAS_PRO_ID)
    REFERENCES PROVAS (PRO_ID)
    ON DELETE SET NULL;
 
ALTER TABLE ESTATISTICAS_PROVAS_USUARIOS ADD CONSTRAINT FK_ESTATISTICAS_PROVAS_USUARIOS_3
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE SET NULL;
 
ALTER TABLE USUARIOS_INSCRITOS ADD CONSTRAINT FK_USUARIOS_INSCRITOS_2
    FOREIGN KEY (FK_PROVAS_PRO_ID)
    REFERENCES PROVAS (PRO_ID)
    ON DELETE SET NULL;
 
ALTER TABLE USUARIOS_INSCRITOS ADD CONSTRAINT FK_USUARIOS_INSCRITOS_3
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE SET NULL;
 
ALTER TABLE USUARIOS_PLANOS ADD CONSTRAINT FK_USUARIOS_PLANOS_2
    FOREIGN KEY (FK_PLANOS_PLA_ID)
    REFERENCES PLANOS (PLA_ID)
    ON DELETE SET NULL;
 
ALTER TABLE USUARIOS_PLANOS ADD CONSTRAINT FK_USUARIOS_PLANOS_3
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE SET NULL;
 
ALTER TABLE EQUIPES_PARTICIPANTES ADD CONSTRAINT FK_EQUIPES_PARTICIPANTES_2
    FOREIGN KEY (FK_EQUIPES_EQP_ID)
    REFERENCES EQUIPES (EQP_ID)
    ON DELETE SET NULL;
 
ALTER TABLE EQUIPES_PARTICIPANTES ADD CONSTRAINT FK_EQUIPES_PARTICIPANTES_3
    FOREIGN KEY (FK_CAMPEONATOS_MODALIDADES_CMM_ID)
    REFERENCES CAMPEONATOS_MODALIDADES (CMM_ID)
    ON DELETE SET NULL;
 
ALTER TABLE REQUISICOES_USUARIOS ADD CONSTRAINT FK_REQUISICOES_USUARIOS_2
    FOREIGN KEY (FK_ATLETICAS_ATL_ID)
    REFERENCES ATLETICAS (ATL_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE AUTORIDADES_MODALIDADES ADD CONSTRAINT FK_AUTORIDADES_MODALIDADES_2
    FOREIGN KEY (FK_MODADLIDADE_ESPORTIVA_MDE_ID)
    REFERENCES MODALIDADES_ESPORTIVAS (MDE_ID);
 
ALTER TABLE EQUIPES_ATLETAS ADD CONSTRAINT FK_EQUIPES_ATLETAS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE SET NULL;