USE ATHLANTIC;

/* JUNÇÃO NO WHERE */
-- ESSE É RUIM PQ A JUNÇÃO FICA COM AS CONDIÇÕES

SELECT USUARIOS.USU_NOME, DENUNCIAS.DNC_DESCRICAO, DENUNCIAS.DNC_DATA
FROM USUARIOS, DENUNCIAS
WHERE USUARIOS.USU_ID = DENUNCIAS.FK_USUARIOS_USU_ID
AND MONTH(DNC_DATA) = 4
AND YEAR(DNC_DATA) = 2023;

SELECT EVE_DESCRICAO, EVE_PRECO, ING_NUMEROINGRESSO, FOR_NOME, FOR_CONTATO
FROM EVENTOS_ESPORTIVOS, INGRESSOS, FORNECEDORES_EVENTOS, FORNECEDORES
WHERE EVENTOS_ESPORTIVOS.EVE_ID = INGRESSOS.FK_EVENTOS_ESPORTIVOS_EVE_ID
AND EVENTOS_ESPORTIVOS.EVE_ID = FORNECEDORES_EVENTOS.FK_EVENTOS_ESPORTIVOS_EVE_ID
AND FORNECEDORES_EVENTOS.FK_FORNECEDORES_FOR_ID = FORNECEDORES.FOR_ID
AND EVE_PRECO BETWEEN 100 AND 300
AND ING_NUMEROINGRESSO > 100;

/* JUNÇÃO POR JOIN */
-- INNER: TEM QUE TER A LIGAÇÃO DOS DOIS LADOS
SELECT USUARIOS.USU_NOME, DENUNCIAS.DNC_DESCRICAO, DENUNCIAS.DNC_DATA FROM USUARIOS
INNER JOIN DENUNCIAS ON USUARIOS.USU_ID = DENUNCIAS.FK_USUARIOS_USU_ID
WHERE MONTH(DNC_DATA) = 4 AND YEAR(DNC_DATA) = 2023;

SELECT EVE_DESCRICAO, EVE_PRECO, ING_NUMEROINGRESSO, FOR_NOME, FOR_CONTATO
FROM EVENTOS_ESPORTIVOS
INNER JOIN INGRESSOS ON INGRESSOS.FK_EVENTOS_ESPORTIVOS_EVE_ID = EVENTOS_ESPORTIVOS.EVE_ID
INNER JOIN FORNECEDORES_EVENTOS ON FORNECEDORES_EVENTOS.FK_EVENTOS_ESPORTIVOS_EVE_ID = EVENTOS_ESPORTIVOS.EVE_ID
INNER JOIN FORNECEDORES ON FORNECEDORES.FOR_ID = FORNECEDORES_EVENTOS.FK_FORNECEDORES_FOR_ID
WHERE EVE_PRECO BETWEEN 100 AND 300
AND ING_NUMEROINGRESSO > 100;