CREATE DATABASE IF NOT EXISTS ATHLANTIC;

USE ATHLANTIC;

CREATE TABLE IF NOT EXISTS ADMINISTRADORES
(
	ADM_ID INT NOT NULL AUTO_INCREMENT,
    ADM_NOME VARCHAR(80) NOT NULL,
    ADM_SENHA VARCHAR(20) NOT NULL,
    ADM_EMAIL VARCHAR(255) NOT NULL,
    PRIMARY KEY (ADM_ID)
);

CREATE TABLE IF NOT EXISTS MODALIDADES_ESPORTIVAS (
	MDE_TIPO_DE_ESPORTE INTEGER NOT NULL,
    MDE_NOME VARCHAR(50) NOT NULL,
    MDE_GENERO INTEGER NOT NULL,
    MDE_ID INTEGER AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (MDE_ID)
);

CREATE TABLE IF NOT EXISTS PLANOS (
	PLA_ID INT AUTO_INCREMENT,
	PLA_CUSTO DEC(8,2) NOT NULL,
	PLA_VANTAGEM VARCHAR(200) NOT NULL,
	PLA_NOME VARCHAR(50) NOT NULL,
	PRIMARY KEY (PLA_ID)
);

CREATE TABLE IF NOT EXISTS COMPRAS(
	CMP_ID INT NOT NULL auto_increment,
	CMP_VALOR_DESCONTO TINYINT NOT NULL,
	CMP_STATUS VARCHAR(255) NOT NULL,
	CMP_DATA date NOT NULL,
	CMP_DESCONTO dec(8,2) NOT NULL,
	primary key (CMP_ID)
);


CREATE TABLE IF NOT EXISTS PATROCINADORES
(
	PTS_ID INT NOT NULL AUTO_INCREMENT,
    PTS_PESSOA_FISICA TINYINT NOT NULL,
    PTS_NOME VARCHAR(60) NOT NULL,
    PTS_CPF_CNPJ VARCHAR(255) NOT NULL,
    PTS_TELEFONE VARCHAR(18) NOT NULL,
    PTS_DATA_CADASTRO DATE NOT NULL,
    PTS_SITE_URL VARCHAR(255) NOT NULL,
    PTS_EMAIL VARCHAR(255) NOT NULL,
    PRIMARY KEY(PTS_ID)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
	FOR_ID INT NOT NULL AUTO_INCREMENT,
    FOR_NOME VARCHAR(60) NOT NULL,
    FOR_DESCRICAO VARCHAR(255),
    FOR_CONTATO VARCHAR(100) NOT NULL,
    FOR_ENDERECO VARCHAR(100) NOT NULL,
    FOR_ATIVO TINYINT NOT NULL,
    PRIMARY KEY(FOR_ID)
);

CREATE TABLE IF NOT EXISTS CHAMADOS(
	CHA_DESCRICAO VARCHAR(150) NOT NULL,
	CHA_NOME VARCHAR(50) NOT NULL,
	CHA_ID INTEGER NOT NULL,
	PRIMARY KEY (CHA_ID)
);

CREATE TABLE IF NOT EXISTS FUNCIONALIDADES(
	FUN_NOME VARCHAR(50) NOT NULL,
	FUN_ID INTEGER NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(FUN_ID)
);

CREATE TABLE IF NOT EXISTS CARGOS(
	CAR_ID INTEGER NOT NULL AUTO_INCREMENT,
	CAR_NOME VARCHAR(30) NOT NULL,
	PRIMARY KEY (CAR_ID)
);

-- FK
CREATE TABLE IF NOT EXISTS ATLETICAS(
	ATL_ID INT NOT NULL AUTO_INCREMENT,
    ATL_NOME VARCHAR(80) NOT NULL,
    ATL_LEMA VARCHAR(50) NOT NULL,
    ATL_ATIVO TINYINT NOT NULL,
    ATL_DESCRICAO VARCHAR(200) NOT NULL,
    ATL_LOGO LONGBLOB NOT NULL,
    ATL_INSTITUICAO_ENSINO VARCHAR(255) NOT NULL,
    FK_ADMINISTRADORES_ADM_ID INT NOT NULL,
    PRIMARY KEY(ATL_ID),
    FOREIGN KEY(FK_ADMINISTRADORES_ADM_ID) REFERENCES ADMINISTRADORES(ADM_ID)
);

CREATE TABLE IF NOT EXISTS USUARIOS(
	USU_ID INT NOT NULL AUTO_INCREMENT,
	USU_SENHA VARCHAR(20) NOT NULL,
	USU_INSTITUICAO_ENSINO VARCHAR(80) NOT NULL,
	USU_ATIVO TINYINT NOT NULL,
	USU_FOTO VARCHAR(125) NOT NULL,
	USU_NUMERO VARCHAR(80) NOT NULL,
	USU_DESCRICAO VARCHAR(150) NOT NULL,
	USU_EMAIL VARCHAR(150) NOT NULL,
	ATL_ID_FK INT NOT NULL,
    FK_EQUIPES_EQP_ID INT NOT NULL,
	PRIMARY KEY (USU_ID),
	FOREIGN KEY (ATL_ID_FK) REFERENCES ATLETICAS(ATL_ID)
);

CREATE TABLE IF NOT EXISTS REQUISICOES_USUARIOS 
(
	REQ_ID INT NOT NULL AUTO_INCREMENT,
    REQ_NOME_USUARIO VARCHAR(50) NOT NULL,
    REQ_SENHA VARCHAR(20) NOT NULL,
    REQ_EMAIL VARCHAR(100) NOT NULL,
    REQ_CONFIRMAR_SENHA VARCHAR(20) NOT NULL,
    FK_ATLETICAS_ATL_ID INT NOT NULL,
    PRIMARY KEY(REQ_ID),
    FOREIGN KEY(FK_ATLETICAS_ATL_ID) REFERENCES ATLETICAS(ATL_ID)
);

CREATE TABLE IF NOT EXISTS REQUISICOES_ATLETICAS 
(
	 REQ_ID INT NOT NULL AUTO_INCREMENT,
	 REQ_NOME_USUARIO VARCHAR(50) NOT NULL,
	 REQ_INSTITUIÇÃO_ENSINO VARCHAR(80)  NOT NULL,
	 REQ_SENHA VARCHAR(20) NOT NULL,
	 REQ_EMAIL VARCHAR(100) NOT NULL,
	 REQ_CONFIRMAR_SENHA VARCHAR(20) NOT NULL,
	 REQ_NOME_ATLETICA VARCHAR(50) NOT NULL,
	 REQ_LOGO_ATLETICA VARCHAR(255) NOT NULL,
	 REQ_DESCRICAO_ATLETICA VARCHAR(100) NOT NULL,
	 FK_ADMINISTRADORES_ADM_ID INT NOT NULL,
	 PRIMARY KEY(REQ_ID),
	 FOREIGN KEY(FK_ADMINISTRADORES_ADM_ID) REFERENCES ADMINISTRADORES(ADM_ID)
);

CREATE TABLE IF NOT EXISTS EVENTOS_ESPORTIVOS (
	EVE_ID INT NOT NULL AUTO_INCREMENT,
    EVE_TIPOENTRADA BOOL NOT NULL,
    EVE_ENDERECOEVENTO VARCHAR(120) NOT NULL,
    EVE_NOME VARCHAR(60) NOT NULL,
    EVE_IMAGEMPROMOCIONAL LONGBLOB NOT NULL,
    EVE_DESCRICAO VARCHAR(255) NOT NULL,
    EVE_DATAEVENTO DATE NOT NULL,
    EVE_PRECO DOUBLE NOT NULL,
    FK_ATLETICAS_ATL_ID INT NOT NULL,
    PRIMARY KEY(EVE_ID),
    FOREIGN KEY(FK_ATLETICAS_ATL_ID) REFERENCES ATLETICAS(ATL_ID)
);

CREATE TABLE IF NOT EXISTS EVENTOS_SOCIAIS(
	EVS_ID INT NOT NULL,
	EVE_ENDERECOEVENTO VARCHAR(120) NOT NULL,
	EVE_NOME VARCHAR(60) NOT NULL,
	EVE_IMAGEMPROMOCIONAL LONGBLOB NOT NULL,
	EVE_DESCRICAO VARCHAR(255) NOT NULL,
	EVE_DATAEVENTO DATE NOT NULL,
	EVE_PRECO DOUBLE NOT NULL,
	FK_ATLETICAS_ATL_ID INT NOT NULL,
	PRIMARY KEY (EVS_ID),
	FOREIGN KEY(FK_ATLETICAS_ATL_ID) REFERENCES ATLETICAS(ATL_ID)
);

CREATE TABLE IF NOT EXISTS PATROCINADORES_EVENTOS
(
	PTE_ID INT NOT NULL AUTO_INCREMENT,
    FK_PATROCINADORES_PTS_ID INT NOT NULL,
    FK_EVENTOS_SOCIAIS_EVS_ID INT NOT NULL,
    FK_EVENTOS_ESPORTIVOS_EVE_ID INT NOT NULL,
    PRIMARY KEY (PTE_ID),
    FOREIGN KEY (FK_PATROCINADORES_PTS_ID) REFERENCES PATROCINADORES(PTS_ID),
    FOREIGN KEY (FK_EVENTOS_SOCIAIS_EVS_ID) REFERENCES EVENTOS_SOCIAIS(EVS_ID),
    FOREIGN KEY (FK_EVENTOS_ESPORTIVOS_EVE_ID) REFERENCES EVENTOS_ESPORTIVOS(EVE_ID)
);

CREATE TABLE IF NOT EXISTS PATROCINIOS(
	PAT_ID INT NOT NULL AUTO_INCREMENT,
    PAT_DESCRICAO VARCHAR(255) NOT NULL,
    PAT_DATAINICIAL DATE NOT NULL,
    PAT_DATAFINAL DATE NOT NULL,
    PAT_IMAGEM LONGBLOB NOT NULL,
    PAT_NOME VARCHAR(255) NOT NULL,
    PAT_VALOR DOUBLE NOT NULL,
    PRIMARY KEY(PAT_ID),
    FK_ATLETICAS_ATL_ID INT NOT NULL,
    FK_PATROCINDORES_PTS_ID INT NOT NULL,
    FOREIGN KEY(FK_PATROCINDORES_PTS_ID) REFERENCES PATROCINADORES(PTS_ID),
    FOREIGN KEY(FK_ATLETICAS_ATL_ID) REFERENCES ATLETICAS(ATL_ID)
);

CREATE TABLE IF NOT EXISTS EQUIPES_ATLETAS(
    ETL_ID INTEGER NOT NULL AUTO_INCREMENT,
    FK_USUARIOS_USU_ID INTEGER NOT NULL,
    PRIMARY KEY (ETL_ID),
    FOREIGN KEY (FK_USUARIOS_USU_ID) REFERENCES USUARIOS(USU_ID)
);

CREATE TABLE IF NOT EXISTS EQUIPES(
	EQP_ID INTEGER AUTO_INCREMENT NOT NULL,
    EQP_TREINADOR VARCHAR(50) NOT NULL,
    FK_ATLETICAS_ATL_ID INTEGER NOT NULL,
    FK_MODALIDADES_ESPORTIVAS_MDE_ID INTEGER NOT NULL,
    FK_EQUIPES_ATLETAS_ETL_ID INTEGER NOT NULL,
    PRIMARY KEY (EQP_ID),
    FOREIGN KEY (FK_ATLETICAS_ATL_ID) REFERENCES ATLETICAS(ATL_ID),
    FOREIGN KEY (FK_MODALIDADES_ESPORTIVAS_MDE_ID) REFERENCES MODALIDADES_ESPORTIVAS (MDE_ID),
    FOREIGN KEY (FK_EQUIPES_ATLETAS_ETL_ID) REFERENCES EQUIPES_ATLETAS (ETL_ID)
);

CREATE TABLE IF NOT EXISTS CAMPEONATOS_MODALIDADES(
    CMM_ID INTEGER NOT NULL AUTO_INCREMENT,
    FK_MODALIDADES_ESPORTIVAS_MDE_ID INTEGER NOT NULL,
    FK_EVENTOS_ESPORTIVOS_EVE_ID INTEGER NOT NULL,
    PRIMARY KEY (CMM_ID),
    FOREIGN KEY (FK_MODALIDADES_ESPORTIVAS_MDE_ID) REFERENCES MODALIDADES_ESPORTIVAS(MDE_ID),
    FOREIGN KEY (FK_EVENTOS_ESPORTIVOS_EVE_ID) REFERENCES EVENTOS_ESPORTIVOS(EVE_ID)   
);

CREATE TABLE IF NOT EXISTS AUTORIDADES_MODALIDADES(
    ATE_ID INTEGER AUTO_INCREMENT NOT NULL,
    FK_MODALIDADE_ESPORTIVA_MDE_ID INTEGER NOT NULL,
    PRIMARY KEY (ATE_ID),
    FOREIGN KEY (FK_MODALIDADE_ESPORTIVA_MDE_ID) REFERENCES MODALIDADES_ESPORTIVAS (MDE_ID)
);

CREATE TABLE IF NOT EXISTS AUTORIDADES( 
	ATD_MODALIDADE_ESPORTIVA INTEGER NOT NULL, 
    ATD_CERTIFICACAO VARCHAR(30) NOT NULL,
    ATD_TELEFONE VARCHAR(15) NOT NULL,
    ATD_IDENTIFICACAO_FISCAL VARCHAR(20),
    ATD_NOME VARCHAR(50),
    ATD_ID INTEGER NOT NULL AUTO_INCREMENT, 
    ATD_EMAIL VARCHAR(50) NOT NULL, 
    ATD_FUNCAO VARCHAR(30) NOT NULL, 
    FOREIGN KEY (ATD_MODALIDADE_ESPORTIVA) REFERENCES AUTORIDADES_MODALIDADES(ATE_ID),
	PRIMARY KEY(ATD_ID)
);

CREATE TABLE IF NOT EXISTS PROVAS(
    PRO_DIA DATE NOT NULL,
    PRO_HORARIO DATETIME NOT NULL,
    PRO_LOCAL VARCHAR(50) NOT NULL,
    PRO_ID INTEGER AUTO_INCREMENT NOT NULL,
    FK_CAMPEONATOS_MODALIDADES_CMM_ID INTEGER NOT NULL,
    PRIMARY KEY (PRO_ID),
    FOREIGN KEY (FK_CAMPEONATOS_MODALIDADES_CMM_ID) REFERENCES CAMPEONATOS_MODALIDADES (CMM_ID)
);

CREATE TABLE IF NOT EXISTS JOGOS(
    JOG_HORARIO DATETIME NOT NULL,
    JOG_EQPB_RESULTADO_FINAL INTEGER NOT NULL,
	JOG_EQPA_RESULTADO_FINAL INTEGER NOT NULL,
    JOG_DIA DATE NOT NULL,
    JOG_ID INTEGER AUTO_INCREMENT NOT NULL,
    JOG_LOCAL VARCHAR(50) NOT NULL,
    FK_CAMPEONATOS_MODALIDADES_CMM_ID INTEGER NOT NULL,
    PRIMARY KEY (JOG_ID),
    FOREIGN KEY (FK_CAMPEONATOS_MODALIDADES_CMM_ID) REFERENCES CAMPEONATOS_MODALIDADES (CMM_ID)
);

CREATE TABLE IF NOT EXISTS ARBITRO_PROVAS(
	ABP_ID INTEGER AUTO_INCREMENT NOT NULL,
    ABP_FUNCAO INTEGER NOT NULL,
    FK_PROVAS_PRO_ID INTEGER NOT NULL,
    FK_AUTORIDADES_ATD_ID INTEGER NOT NULL,
    PRIMARY KEY (ABP_ID),
    FOREIGN KEY (FK_PROVAS_PRO_ID) REFERENCES PROVAS (PRO_ID),
    FOREIGN KEY (FK_AUTORIDADES_ATD_ID) REFERENCES AUTORIDADES (ATD_ID)
);

CREATE TABLE IF NOT EXISTS EQUIPES_JOGOS(
	EJQ_ID INTEGER NOT NULL AUTO_INCREMENT,
	FK_JOGOS_JOG_ID INTEGER NOT NULL,
    FK_EQUIPES_EQP_ID INTEGER NOT NULL,
	PRIMARY KEY (EJQ_ID),
	FOREIGN KEY (FK_JOGOS_JOG_ID) REFERENCES JOGOS (JOG_ID),
    FOREIGN KEY (FK_EQUIPES_EQP_ID) REFERENCES EQUIPES (EQP_ID)
);

CREATE TABLE IF NOT EXISTS EQUIPES_PARTICIPANTES(
	EPA_ID INTEGER AUTO_INCREMENT NOT NULL,
    FK_CAMPEONATOS_MODALIDADES_CMM_ID INTEGER NOT NULL,
    FK_EQUIPES_EQP_ID INTEGER NOT NULL,
    PRIMARY KEY (EPA_ID),
	FOREIGN KEY (FK_CAMPEONATOS_MODALIDADES_CMM_ID) REFERENCES CAMPEONATOS_MODALIDADES (CMM_ID),
    FOREIGN KEY (FK_EQUIPES_EQP_ID) REFERENCES EQUIPES (EQP_ID)
);

CREATE TABLE IF NOT EXISTS ENTRADAS(
    ENT_DESCRICAO VARCHAR(7) NOT NULL,
    ENT_DATA DATE NOT NULL,
    ENT_VALOR DOUBLE NOT NULL,
    ENT_NOME VARCHAR(100) NOT NULL,
    ENT_ID INTEGER AUTO_INCREMENT NOT NULL,
    FK_ATLETICAS_ATL_ID INTEGER NOT NULL,
    PRIMARY KEY (ENT_ID),
    FOREIGN KEY (FK_ATLETICAS_ATL_ID) REFERENCES ATLETICAS(ATL_ID)
);

CREATE TABLE IF NOT EXISTS DESPESAS(
    DEP_NOME VARCHAR(120) NOT NULL,
    DEP_DESCRICAO VARCHAR(250) NOT NULL,
    DEP_ID_ENTIDADE INTEGER,
    DEP_DATA DATE NOT NULL,
    DEP_VALOR DOUBLE NOT NULL,
    DEP_ID INTEGER NOT NULL AUTO_INCREMENT,
    DEP_TIPO ENUM('EVENTO', 'PRODUTO'),
    DEP_FORMA_PAGAMENTO ENUM('CREDITO', 'PIX', 'DINHEIRO'),
    FK_ATLETICAS_ATL_ID INTEGER NOT NULL,
    PRIMARY KEY (DEP_ID),
    FOREIGN KEY(FK_ATLETICAS_ATL_ID) REFERENCES ATLETICAS(ATL_ID)
);

CREATE TABLE IF NOT EXISTS USUARIOS_PLANOS (
	USP_ID INT AUTO_INCREMENT,
	FK_PLANOS_PLA_ID INT NOT NULL,
	FK_USUARIOS_USU_ID INT NOT NULL,
	PRIMARY KEY (USP_ID),
	FOREIGN KEY (FK_USUARIOS_USU_ID) REFERENCES USUARIOS(USU_ID),
	FOREIGN KEY (FK_PLANOS_PLA_ID) REFERENCES PLANOS(PLA_ID)
);

CREATE TABLE IF NOT EXISTS PLANOS_ATLETICA (
    PLA_ID INT AUTO_INCREMENT,
    FK_PLA_ID INT NOT NULL,
    FK_ATL_ID INT NOT NULL,
    PRIMARY KEY (PLA_ID),
    FOREIGN KEY (FK_PLA_ID) REFERENCES PLANOS(PLA_ID),
    FOREIGN KEY (FK_ATL_ID) REFERENCES ATLETICAS(ATL_ID)
);

CREATE TABLE IF NOT EXISTS INGRESSOS (
	ING_ID INT NOT NULL AUTO_INCREMENT,
	ING_NUMEROINGRESSO INT NOT NULL,
	FK_EVENTOS_SOCIAIS_EVS_ID INT NOT NULL,
	FK_EVENTOS_ESPORTIVOS_EVE_ID INT NOT NULL,
	PRIMARY KEY (ING_ID),
	FOREIGN KEY (FK_EVENTOS_SOCIAIS_EVS_ID) REFERENCES EVENTOS_SOCIAIS(EVS_ID),
	FOREIGN KEY (FK_EVENTOS_ESPORTIVOS_EVE_ID) REFERENCES EVENTOS_ESPORTIVOS(EVE_ID)
);

CREATE TABLE IF NOT EXISTS LOTES_INGRESSOS (
	LOI_ID INT AUTO_INCREMENT,
	LOI_QUANTIDADE_PENDENTE INT NOT NULL,
	LOI_QUANTIDADE_DISPONIVEL INT NOT NULL,
	LOI_VALOR DEC(8,2) NOT NULL,
	LOI_VENDAMINIMA INT NOT NULL,
	FK_INGRESSOS_ING_ID INT NOT NULL,
	PRIMARY KEY (LOI_ID),
	FOREIGN KEY (FK_INGRESSOS_ING_ID) REFERENCES INGRESSOS(ING_ID)
);

CREATE TABLE IF NOT EXISTS COMPRAS_INGRESSOS (
	CPI_ID INT AUTO_INCREMENT,
	CPI_DATA_COMPRA INT NOT NULL,
	CPI_STATUS ENUM('FINALIZADO', 'PENDENTE', 'CANCELADO'),
	FK_USUARIOS_USU_ID INT NOT NULL,
	FK_LOTES_INGRESSOS_LOI_ID INT NOT NULL,
	PRIMARY KEY (CPI_ID),
	FOREIGN KEY (FK_USUARIOS_USU_ID) REFERENCES USUARIOS(USU_ID),
	FOREIGN KEY (FK_LOTES_INGRESSOS_LOI_ID) REFERENCES LOTES_INGRESSOS(LOI_ID)
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
	PRO_ID INT AUTO_INCREMENT,
	PRO_NOME VARCHAR(60) NOT NULL,
	PRO_DESCRICAO VARCHAR(255) NOT NULL,
	PRO_QUANTIDADE INT NOT NULL,
	PRO_STATUS VARCHAR(30) NOT NULL,
	PRO_EXCLUSIVIDADE TINYINT NOT NULL,
	PRO_EXCLUIDO TINYINT NOT NULL,
	FK_FORNECEDORES_FOR_ID INT NOT NULL,
	PRIMARY KEY (PRO_ID),
	FOREIGN KEY (FK_FORNECEDORES_FOR_ID) REFERENCES FORNECEDORES(FOR_ID)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_IMAGENS(
	PDI_ID INT AUTO_INCREMENT,
	PDI_IMAGEM VARCHAR (255) NOT NULL,
	FK_PRO_ID INT NOT NULL,
	PRIMARY KEY (PDI_ID),
	FOREIGN KEY (FK_PRO_ID) REFERENCES PRODUTOS(PRO_ID)
);

CREATE TABLE IF NOT EXISTS LOTES_PRODUTOS (
	LOP_ID INT AUTO_INCREMENT,
	LOP_QUANTIDADE_PENDENTE INT NOT NULL,
	LOP_PRECO_PRODUTO DEC(8,2) NOT NULL,
	LOP_QUANTIDADE_DISPONIVEL INT NOT NULL,
	LOP_VENDAMINIMA INT NOT NULL,
	FK_PRODUTOS_PRO_ID INT NOT NULL,
	PRIMARY KEY (LOP_ID),
	FOREIGN KEY (FK_PRODUTOS_PRO_ID) REFERENCES PRODUTOS(PRO_ID)
);

CREATE TABLE IF NOT EXISTS ITEMS_COMPRAS (
	ITC_ID INT AUTO_INCREMENT,
	ITS_QUANTIDADE INT NOT NULL,
	FK_COMPRAS_CMP_ID INT NOT NULL,
	FK_LOTES_PRODUTOS_LOP_ID INT NOT NULL,
	PRIMARY KEY (ITC_ID),
	FOREIGN KEY (FK_COMPRAS_CMP_ID) REFERENCES COMPRAS(CMP_ID),
	FOREIGN KEY (FK_LOTES_PRODUTOS_LOP_ID) REFERENCES LOTES_PRODUTOS(LOP_ID)
);

CREATE TABLE COMENTARIOS(
	CMT_ID INT NOT NULL AUTO_INCREMENT,
	FK_USU_ID INT NOT NULL,
	CMT_TEXTO VARCHAR(255) NOT NULL,
	CMT_CURTIDAS INT NOT NULL,
	CMT_FK_ID_POSTAGEM INT NOT NULL,
	CMT_TIPO_POSTAGEM INT NOT NULL,
	PRIMARY KEY (CMT_ID),
	FOREIGN KEY (FK_USU_ID) REFERENCES USUARIOS(USU_ID)
);

CREATE TABLE IF NOT EXISTS USUARIOS_CHAMADOS(
	USC_ID INT NOT NULL AUTO_INCREMENT,
	FK_IDUSUARIO INT NOT NULL,
	FK_IDCHA_ID INT NOT NULL,
	PRIMARY KEY (USC_ID),
	FOREIGN KEY (FK_IDUSUARIO) REFERENCES USUARIOS(USU_ID),
	FOREIGN KEY (FK_IDCHA_ID) REFERENCES CHAMADOS(CHA_ID)
);

CREATE TABLE IF NOT EXISTS DENUNCIAS(
	DNC_ID INT NOT NULL AUTO_INCREMENT,
	FK_USU_ID INT NOT NULL,
	DNC_DESCRICAO VARCHAR(255) NOT NULL,
	DNC_TIPO_DENUNCIA INT NOT NULL,
	DNC_DATA DATE NOT NULL,
	DNC_FK_ID_COMENTARIO_POSTAGEM INT NOT NULL,
	PRIMARY KEY(DNC_ID),
	FOREIGN KEY(FK_USU_ID) REFERENCES USUARIOS(USU_ID)
);

CREATE TABLE IF NOT EXISTS VOTACAO(
	VOT_ID INTEGER NOT NULL AUTO_INCREMENT,
	VOT_PRAZO DATE NOT NULL,
	FK_CHA_ID INTEGER NOT NULL,
	PRIMARY KEY (VOT_ID),
	FOREIGN KEY (FK_CHA_ID) REFERENCES CHAMADOS(CHA_ID)
);

CREATE TABLE IF NOT EXISTS VOTACOES_USUARIOS(
	VTS_ID INTEGER NOT NULL,
	VTS_DATA DATE NOT NULL,
	VTS_STATUS TINYINT NOT NULL,
	USU_FK_ID INTEGER NOT NULL,
	VOT_FK_ID INTEGER NOT NULL,
	PRIMARY KEY (VTS_ID),
	FOREIGN KEY (USU_FK_ID) REFERENCES USUARIOS(USU_ID),
	FOREIGN KEY (VOT_FK_ID) REFERENCES VOTACAO(VOT_ID)
);


CREATE TABLE IF NOT EXISTS CARGOS_FUNCIONALIDADES(
	PRI_ID INTEGER NOT NULL AUTO_INCREMENT,
	PRI_POSSUI TINYINT NOT NULL,
	FK_FUN_ID INTEGER NOT NULL,
	FK_CAR_ID INTEGER NOT NULL,
	PRIMARY KEY (PRI_ID),
	FOREIGN KEY (FK_FUN_ID) REFERENCES FUNCIONALIDADES(FUN_ID),
	FOREIGN KEY (FK_CAR_ID) REFERENCES CARGOS(CAR_ID)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
	PAG_ID INTEGER NOT NULL AUTO_INCREMENT,
	PAG_CONDICAO VARCHAR(15) NOT NULL,
	PAG_DATA DATE NOT NULL,
	PAG_VALOR_PAGO DEC(8,2) NOT NULL,
	FK_USER_ID INTEGER NOT NULL,
	PRIMARY KEY (PAG_ID),
	FOREIGN KEY (FK_USER_ID) REFERENCES USUARIOS(USU_ID)
);

CREATE TABLE IF NOT EXISTS USUARIOS_CARGOS(
	NOT_ID INT NOT NULL AUTO_INCREMENT,
	NOT_TIPO VARCHAR(30) NOT NULL,
	NOT_TITULO VARCHAR(50) NOT NULL,
	NOT_DESCRICAO VARCHAR(100) NOT NULL,
	FK_USUARIOS_USU_ID INT NOT NULL,
	PRIMARY KEY (NOT_ID),
	FOREIGN KEY (FK_USUARIOS_USU_ID) REFERENCES USUARIOS(USU_ID)
);

CREATE TABLE IF NOT EXISTS POSTAGEM_GERAL(
	PST_DESCRICAO VARCHAR(255) NOT NULL,
	PST_CURTIDAS INT NOT NULL,
	PST_DATA DATE NOT NULL,
	PST_IMAGEM LONGBLOB NOT NULL,
	PST_ID INT NOT NULL,
	PSP_ID INT NOT NULL,
	PSP_TITULO VARCHAR(25) NOT NULL,
	PSE_ID INT NOT NULL,
	PSE_TITULO VARCHAR(25) NOT NULL,
	POSTAGEM_GERAL_TIPO INT NOT NULL,
	FK_EVENTOS_EVS_ID INT NOT NULL,
	FK_EVENTOS_EVE_ID INT NOT NULL,
	FK_PRODUTOS_PRO_ID INT NOT NULL,
	FK_USUARIOS_USU_ID INT NOT NULL,

	PRIMARY KEY (PST_DESCRICAO),
	FOREIGN KEY (FK_EVENTOS_EVS_ID) REFERENCES EVENTOS_SOCIAIS (EVS_ID),
	FOREIGN KEY (FK_EVENTOS_EVE_ID) REFERENCES EVENTOS_ESPORTIVOS (EVE_ID),
	FOREIGN KEY (FK_PRODUTOS_PRO_ID) REFERENCES PRODUTOS(PRO_ID),
	FOREIGN KEY (FK_USUARIOS_USU_ID) REFERENCES USUARIOS(USU_ID)
);

ALTER TABLE USUARIOS ADD CONSTRAINT FK_EQUIPES_EQP_ID FOREIGN KEY(FK_EQUIPES_EQP_ID) REFERENCES EQUIPES(EQP_ID);
