CREATE SCHEMA IF NOT EXISTS TESTE_INSERT_EXCEL;
USE TESTE_INSERT_EXCEL;

SELECT * FROM ESTADOS;

SELECT 1+1;

CREATE TABLE IF NOT EXISTS ESTADOS(
	ID INT NOT NULL AUTO_INCREMENT,
    CODIGO INT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    SIGLA CHAR(2) NOT NULL,
    PRIMARY KEY(ID)
);

INSERT INTO ESTADOS(CODIGO, NOME, SIGLA) SELECT DISTINCT CD_UF, NM_UF, NM_UF_SIGLA FROM MUNICIPIOS WHERE NM_UF <> '' ORDER BY NM_UF;